### ISSUE TITLE
Complexity of the application

### ISSUE THREAD

**Issue by grimcoder** [fedosejev/shopping-list-react-flux#4]
Artemij hi again. I am not sure whether it is the most appropriate place to ask this kind of questions, and this is not really an issue, but taking into account your brisk responsiveness (thanks), here is what I would like to ask:
In your recent work "React.js Essentials" you are giving this application as an example of the "small project": 
" It works for small projects too; here is an example of a shopping list built with React: http://fedosejev.github.io/shopping-list-react."
However being small functionally it is not that small in regard to the lines of code. For example I could build application with the same functionality using Angular using probably 4 times less code. 
That being said what was your intention to use flux here (considering the size of the project)? Is this a good practice to use flux with react on the project of this size or rather an  overkill in order to shed light on the flux. 
Do you recommend using flux for one list application?

**Comment by grimcoder** [comment]
If I would want to hook up this application what would be the best place to do it ? ListItemStore ?

**Comment by fedosejev** [comment]
Hey @grimcoder, thanks for your questions!

You're right - this app can be built with less code in Angular. My goal here is to provide the most simplistic example of how to use React with Flux. Normally you can find examples of Flux in larger apps - which can be harder to understand. And that makes sense, because Flux is designed to deal with more complex apps.

You're right again - Flux is an overkill in this case, but on purpose: to demonstrate it in a context of a simple app.

I would not recommend to use Flux, unless you know exactly what problem it's going to solve for you.

**Comment by fedosejev** [comment]
@grimcoder in your second question - can you please explain a bit more what are you trying to achieve?
